services:
  - type: web
    name: safecall
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input --clear && python setup_database.py"
    startCommand: "gunicorn safecall.wsgi:application"
    # You need to manually create a PostgreSQL database in the Render dashboard
    # and set the DATABASE_URL environment variable in your service
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,safecall.onrender.com"
      - key: DATABASE_URL
        # This will be automatically set when the database is created
        fromDatabase:
          name: safecall_db
          property: connectionString
      - key: STATIC_ROOT
        value: /opt/render/project/src/staticfiles
      - key: STATIC_URL
        value: /static/
      - key: WHITENOISE_ALLOW_ALL_ORIGINS
        value: "true"
      - key: WHITENOISE_USE_FINDERS
        value: "true"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: EMAIL_HOST
        sync: false  
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: NEWSAPI_KEY
        sync: false

# Define the database separately - this needs to be created first
databases:
  - name: safecall_db
    databaseName: safecall
    plan: free
    # Migrations will be run after the database is connected
    ipAllowList: [] # Allow all connections 