# Generated by Django 5.1.7 on 2025-03-18 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adhaar', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('Robbery', 'Robbery'), ('Assault', 'Assault'), ('Threats', 'Threats'), ('Burglary', 'Burglary'), ('Vandalism', 'Vandalism'), ('Fraud', 'Fraud'), ('Harassment', 'Harassment'), ('Theft', 'Theft'), ('Domestic Violence', 'Domestic Violence'), ('Sexual Assault', 'Sexual Assault'), ('Kidnapping', 'Kidnapping'), ('Stalking', 'Stalking'), ('Drunk Driving', 'Drunk Driving'), ('Hit and Run', 'Hit and Run'), ('Drug Offenses', 'Drug Offenses'), ('Public Intoxication', 'Public Intoxication'), ('Trespassing', 'Trespassing'), ('Hate Crimes', 'Hate Crimes'), ('Murder', 'Murder'), ('Arson', 'Arson'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('incident_location', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_date', models.DateField()),
                ('incident_time', models.CharField(choices=[('Midnight', '12:00 AM - 12:59 AM'), ('Morning', '6:00 AM - 11:59 AM'), ('Noon', '12:00 PM - 12:59 PM'), ('Afternoon', '1:00 PM - 5:59 PM'), ('Evening', '6:00 PM - 8:59 PM'), ('Night', '9:00 PM - 11:59 PM')], max_length=20)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicuser')),
            ],
        ),
    ]
