# Generated by Django 5.1.7 on 2025-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='password',
            field=models.CharField(default='defaultpassword123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicuser',
            name='password',
            field=models.CharField(default='abcd', max_length=255),
            preserve_default=False,
        ),
    ]
