# Generated by Django 5.1.7 on 2025-03-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('investigating_officer', models.CharField(max_length=100)),
                ('sections_applied', models.TextField(help_text='IPC Sections applied')),
                ('witness_statements', models.TextField(blank=True, null=True)),
                ('evidence_details', models.TextField(blank=True, null=True)),
                ('investigation_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Filed', 'Filed'), ('Under Investigation', 'Under Investigation'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='investigation_updates/')),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.fir')),
            ],
        ),
    ]
