# Generated by Django 5.1.7 on 2025-03-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fir_investigationupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationupdate',
            name='fir',
        ),
        migrations.CreateModel(
            name='EmergencyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicuser')),
            ],
        ),
        migrations.DeleteModel(
            name='FIR',
        ),
        migrations.DeleteModel(
            name='InvestigationUpdate',
        ),
    ]
