# Generated by Django 5.1.7 on 2025-03-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_policestation_password_publicuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='email',
            field=models.EmailField(default='abcd', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
