# Generated by Django 5.1.7 on 2025-03-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_investigationupdate_fir_emergencylocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='EmergencyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('responded', 'Police Responded'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('device_info', models.JSONField(default=dict)),
                ('emergency_notes', models.TextField(blank=True, null=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.emergencytracker')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='EmergencyLocation',
        ),
    ]
