# Generated by Django 5.1.7 on 2025-03-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_policestation_latitude_policestation_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationhistory',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='publicuser',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='location_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.publicuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='EmergencyTracker',
        ),
        migrations.DeleteModel(
            name='LocationHistory',
        ),
    ]
