# Generated by Django 5.1.7 on 2025-03-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_locationhistory_emergency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='location_sharing_enabled',
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emergencyalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicuser')),
            ],
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
