# Generated by Django 5.1.7 on 2025-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_publicuser_last_location_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyalert',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='locationhistory',
            name='emergency_alert',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Responded', 'Responded'), ('Resolved', 'Resolved'), ('False_Alarm', 'False Alarm')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='location_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
