# Generated by Django 5.1.7 on 2025-03-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_timestamp_emergencyalert_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='last_latitude',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='last_longitude',
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userlocation'),
        ),
        migrations.DeleteModel(
            name='LocationHistory',
        ),
    ]
