# Generated by Django 5.1.7 on 2025-03-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_emergencyalert_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='location_tracking_enabled',
        ),
        migrations.DeleteModel(
            name='EmergencyAlert',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
