# Generated by Django 5.1.7 on 2025-03-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
