# Generated by Django 5.1.7 on 2025-03-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_complaintmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintMessage',
        ),
    ]
