# Generated by Django 5.1.7 on 2025-03-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
