# Generated by Django 5.1.7 on 2025-03-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
