# Generated by Django 5.1.7 on 2025-03-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
