# Generated by Django 5.1.7 on 2025-03-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='additional_evidence',
            field=models.FileField(blank=True, null=True, upload_to='additional_evidence/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='spot_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='core.complaint')),
            ],
        ),
    ]
