# Generated by Django 5.1.7 on 2025-03-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_complaint_additional_evidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='additional_evidence',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='spot_location',
        ),
        migrations.RemoveField(
            model_name='witness',
            name='complaint',
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_evidence', models.FileField(blank=True, null=True, upload_to='fir_evidence/')),
                ('spot_location', models.CharField(blank=True, max_length=255, null=True)),
                ('police_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fir', to='core.complaint')),
            ],
        ),
        migrations.AddField(
            model_name='witness',
            name='fir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='core.fir'),
        ),
    ]
