# Generated by Django 5.1.7 on 2025-03-28 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_complaint_additional_evidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='additional_evidence',
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fir_evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_evidence', to='core.fir')),
            ],
        ),
    ]
