# Generated by Django 5.1.7 on 2025-03-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_fir_additional_evidence_evidence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evidence',
            new_name='FIREvidence',
        ),
    ]
