# Generated by Django 5.1.7 on 2025-03-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_evidence_firevidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='evidence',
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='incident_location',
            field=models.TextField(default='Location not specified'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
