# Generated by Django 5.1.7 on 2025-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_complaintlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_VERIFY', 'User Verified'), ('USER_SUSPEND', 'User Suspended'), ('COMPLAINT_CREATE', 'Complaint Created'), ('COMPLAINT_UPDATE', 'Complaint Updated'), ('COMPLAINT_STATUS', 'Complaint Status Changed'), ('FIR_CREATE', 'FIR Created'), ('FIR_UPDATE', 'FIR Updated'), ('EVIDENCE_UPLOAD', 'Evidence Uploaded'), ('POLICE_CREATE', 'Police Station Created'), ('POLICE_UPDATE', 'Police Station Updated'), ('POLICE_APPROVE', 'Police Station Approved'), ('POLICE_SUSPEND', 'Police Station Suspended')], max_length=20)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('PUBLIC', 'Public User'), ('POLICE', 'Police Station'), ('SYSTEM', 'System')], max_length=10)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
