# Generated by Django 5.1.7 on 2025-04-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_systemlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
