# Generated by Django 5.1.7 on 2025-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='complaint_evidence/'),
        ),
    ]
