# Generated by Django 5.1.7 on 2025-04-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_donation_donor_email_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
    ]
