# Generated by Django 5.1.7 on 2025-05-13 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_donation_donor_email_donation_donor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIRUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.fir')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
