# Generated by Django 5.1.7 on 2025-05-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_firupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FIRUpdate',
        ),
    ]
