# Generated by Django 5.1.7 on 2025-05-13 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_delete_firupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIRDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_descriptions', to='core.fir')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
